//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiNhaTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class NANG_KHIEU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NANG_KHIEU()
        {
            this.TU_NHAN = new HashSet<TU_NHAN>();
        }
    
        public int Ma_NK { get; set; }
        public string Ten_NK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TU_NHAN> TU_NHAN { get; set; }
    }
}
