//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiNhaTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAN_NHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THAN_NHAN()
        {
            this.TU_NHAN = new HashSet<TU_NHAN>();
        }
    
        public string Ma_Than_N { get; set; }
        public string Ho_Ten { get; set; }
        public string Gioi_Tinh { get; set; }
        public Nullable<System.DateTime> Ngay_Sinh { get; set; }
        public string SDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TU_NHAN> TU_NHAN { get; set; }
    }
}
