//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiNhaTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAN_BO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAN_BO()
        {
            this.CONG_VIEC = new HashSet<CONG_VIEC>();
            this.DOT_KHAM_BENH = new HashSet<DOT_KHAM_BENH>();
        }
    
        public string Ma_CB { get; set; }
        public string Ho_Ten { get; set; }
        public string SDT { get; set; }
        public Nullable<System.DateTime> Ngay_Sinh { get; set; }
        public string Mat_Khau { get; set; }
        public string Ma_BP { get; set; }
    
        public virtual BO_PHAN BO_PHAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONG_VIEC> CONG_VIEC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOT_KHAM_BENH> DOT_KHAM_BENH { get; set; }
    }
}
