//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiNhaTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAU_HINH
    {
        public int Ma_CH { get; set; }
        public string Ten_CH { get; set; }
        public Nullable<int> Gia_Tri { get; set; }
    }
}
