//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiNhaTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHEN_THUONG
    {
        public int Ma_KT { get; set; }
        public string Ten_KT { get; set; }
        public string Ma_Tu_N { get; set; }
    
        public virtual TU_NHAN TU_NHAN { get; set; }
    }
}
