//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiNhaTu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUAN_LI_NHA_TUEntities1 : DbContext
    {
        public QUAN_LI_NHA_TUEntities1()
            : base("name=QUAN_LI_NHA_TUEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BO_PHAN> BO_PHAN { get; set; }
        public virtual DbSet<CA_TRUC> CA_TRUC { get; set; }
        public virtual DbSet<CAN_BO> CAN_BO { get; set; }
        public virtual DbSet<CAU_HINH> CAU_HINH { get; set; }
        public virtual DbSet<CONG_VIEC> CONG_VIEC { get; set; }
        public virtual DbSet<DOT_KHAM_BENH> DOT_KHAM_BENH { get; set; }
        public virtual DbSet<KHEN_THUONG> KHEN_THUONG { get; set; }
        public virtual DbSet<NANG_KHIEU> NANG_KHIEU { get; set; }
        public virtual DbSet<THAN_NHAN> THAN_NHAN { get; set; }
        public virtual DbSet<TU_NHAN> TU_NHAN { get; set; }
    }
}
