//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiNhaTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TU_NHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TU_NHAN()
        {
            this.KHEN_THUONG = new HashSet<KHEN_THUONG>();
            this.THAN_NHAN = new HashSet<THAN_NHAN>();
            this.DOT_KHAM_BENH = new HashSet<DOT_KHAM_BENH>();
            this.NANG_KHIEU = new HashSet<NANG_KHIEU>();
        }
    
        public string Ma_Tu_N { get; set; }
        public string Ho_Ten { get; set; }
        public Nullable<System.DateTime> Ngay_Sinh { get; set; }
        public string Gioi_Tinh { get; set; }
        public string Toi_Danh { get; set; }
        public Nullable<System.DateTime> Ngay_Vao_Tu { get; set; }
        public Nullable<System.DateTime> Ngay_Ra_Tu { get; set; }
        public string Tinh_Trang_suc_Khoe { get; set; }
        public Nullable<System.DateTime> Ngay_Duoc_Tham_Nuoi { get; set; }
        public string Muc_Do_Cai_Tao { get; set; }
        public string Tinh_Trang_Giam_Giu { get; set; }
        public Nullable<System.DateTime> Ngay_Kham { get; set; }
        public Nullable<System.DateTime> Ngay_Tai_Kham { get; set; }
        public string Mat_Khau { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHEN_THUONG> KHEN_THUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THAN_NHAN> THAN_NHAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOT_KHAM_BENH> DOT_KHAM_BENH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NANG_KHIEU> NANG_KHIEU { get; set; }
    }
}
